# .pre-commit-config.yaml for MyLinkBio 🚀
# Ensures clean commits, formatting consistency, and secret scanning

repos:
  # --- Basic hygiene hooks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,markdown"]
        exclude: \.svg$
      - id: end-of-file-fixer
        exclude: \.svg$
      - id: check-yaml
      - id: double-quote-string-fixer
        exclude: \.svg$

  # --- Secret scanning with Gitleaks ---
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.26.0
    hooks:
      - id: gitleaks
        args: ["--verbose"]

  # --- Security scanning with Talisman ---
  - repo: https://github.com/thoughtworks/talisman
    rev: v1.37.0
    hooks:
      - id: talisman-commit
        args: ["--githook=pre-commit"]

  # --- Optional: Add Prettier for consistent JS/HTML/CSS formatting ---
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.3.3 # pick latest stable
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|css|scss|html|md)$
